# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build .NET

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies - API
      run: dotnet restore
      working-directory: src/CadCli.Api
    
    - name: Restore dependencies - Tests
      run: dotnet restore
      working-directory: src/CadCli.Tests
      
    - name: Build - API
      run: dotnet build --no-restore
      working-directory: src/CadCli.Api
      
    - name: Build - Tests
      run: dotnet build --no-restore
      working-directory: src/CadCli.Tests
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: src/CadCli.Tests
      
    
    - name: Publish
      run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp
      working-directory: src/CadCli.Api
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: artifact
        path: ${{env.DOTNET_ROOT}}/myapp

    
